In [ ]:
import pandas as pd
df = pd.read_csv('nba.csv')
df

In [ ]:
#How many rows does the NBA dataset have?
df.shape[0]

457

In [ ]:
#Select all rows excluding botton 157 rows using head() function. What is the salary in the last row?
df.head(-157)

,Name,Team,Number,Position,Height,Weight,Age,Salary,College
0,Avery Bradley,Boston Celtics,0,PG,6-2,180,25.0,7730337.0,Texas
1,Jae Crowder,Boston Celtics,99,SF,6-3,235,25.0,6796117.0,Marquette
2,John Holland,Boston Celtics,30,SG,6-4,205,27.0,NaN,Boston University
3,R-J- Hunter,Boston Celtics,28,SG,6-5,185,22.0,1148640.0,Georgia State
4,Jonas Jerebko,Boston Celtics,8,PF,6-6,231,29.0,5000000.0,NaN
...,...,...,...,...,...,...,...,...,...
295,Kyle Anderson,San Antonio Spurs,1,SF,6-9,230,22.0,1142880.0,UCLA
296,Matt Bonner,San Antonio Spurs,15,C,6-1,235,36.0,947276.0,Florida
297,Boris Diaw,San Antonio Spurs,33,C,6-8,250,34.0,7500000.0,NaN
298,Tim Duncan,San Antonio Spurs,21,C,6-11,250,40.0,5250000.0,Wake Forest
299,Manu Ginobili,San Antonio Spurs,20,SG,6-6,205,38.0,2814000.0,NaN

In [ ]:
#Select all rows excluding top 17 rows using tail() function. What is the salary in the first row?
df.tail(-17)

,Name,Team,Number,Position,Height,Weight,Age,Salary,College
17,Wayne Ellington,Brooklyn Nets,21,SG,6-19,200,28.0,1500000.0,North Carolina
18,Rondae Hollis-Jefferson,Brooklyn Nets,24,SG,6-2,220,21.0,1335480.0,Arizona
19,Jarrett Jack,Brooklyn Nets,2,PG,6-21,200,32.0,6300000.0,Georgia Tech
20,Sergey Karasev,Brooklyn Nets,10,SG,6-22,208,22.0,1599840.0,NaN
21,Sean Kilpatrick,Brooklyn Nets,6,SG,6-23,219,26.0,134215.0,Cincinnati
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,6-1,234,20.0,2239800.0,Kentucky
453,Shelvin Mack,Utah Jazz,8,PG,6-3,203,26.0,2433333.0,Butler
454,Raul Neto,NaN,25,PG,6-1,179,24.0,900000.0,NaN
455,Tibor Pleiss,Utah Jazz,21,C,7-3,256,26.0,2900000.0,NaN
456,Jeff Withey,Utah Jazz,24,C,7,231,26.0,947276.0,Kansas

In [ ]:
#How many NA values are present in the column Salary in the NBA dataset?
df['Salary'].isnull().sum()

14

In [ ]:
#How many NA values are present in the column College in the NBA dataset?
df['College'].isnull().sum()

82

In [ ]:
#Drop rows (25,72,63) from the NBA dataset. What is the average age of the players after dropping rows?
#Note: Please do not change the original dataset while solving this assignment.
dropped_rows = df.drop([25,72,63])
dropped_rows['Age'].mean()

26.915742793791573

In [ ]:
#Rename column "Number' to 'Chest Number" and "Weight' to 'weight(lbs) in the NBA dataset.
df.rename( columns = {"Number": "Chest_Number","Weight": "Weight(lbs)"}, inplace = True)
df

,Name,Team,Chest_Number,Position,Height,Weight(lbs),Age,Salary,College
0,Avery Bradley,Boston Celtics,0,PG,6-2,180,25.0,7730337.0,Texas
1,Jae Crowder,Boston Celtics,99,SF,6-3,235,25.0,6796117.0,Marquette
2,John Holland,Boston Celtics,30,SG,6-4,205,27.0,NaN,Boston University
3,R-J- Hunter,Boston Celtics,28,SG,6-5,185,22.0,1148640.0,Georgia State
4,Jonas Jerebko,Boston Celtics,8,PF,6-6,231,29.0,5000000.0,NaN
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,6-1,234,20.0,2239800.0,Kentucky
453,Shelvin Mack,Utah Jazz,8,PG,6-3,203,26.0,2433333.0,Butler
454,Raul Neto,NaN,25,PG,6-1,179,24.0,900000.0,NaN
455,Tibor Pleiss,Utah Jazz,21,C,7-3,256,26.0,2900000.0,NaN
456,Jeff Withey,Utah Jazz,24,C,7,231,26.0,947276.0,Kansas

In [ ]:
#Find the name of the player with highest salary
###df[df['Salary'].max()]
df[df['Salary'] == 25000000]
#Method2
df.sort_values(by = 'Salary', ascending = False)

,Name,Team,Chest_Number,Position,Height,Weight(lbs),Age,Salary,College
109,Kobe Bryant,Los Angeles Lakers,24,SF,6-6,212,37.0,25000000.0,NaN
169,LeBron James,Cleveland Cavaliers,23,SF,6-8,250,31.0,22970500.0,NaN
33,Carmelo Anthony,New York Knicks,7,SF,7-5,240,32.0,22875000.0,Syracuse
251,Dwight Howard,Houston Rockets,12,C,6-11,265,30.0,22359364.0,NaN
339,Chris Bosh,Miami Heat,1,PF,6-11,235,32.0,22192730.0,Georgia Tech
...,...,...,...,...,...,...,...,...,...
273,Alex Stepheson,Memphis Grizzlies,35,PF,6-1,270,28.0,NaN,USC
350,Briante Weber,Miami Heat,12,PG,6-2,165,23.0,NaN,Virginia Commonwealth
353,Dorell Wright,Miami Heat,11,SF,6-9,205,30.0,NaN,NaN
397,Axel Toupane,Denver Nuggets,6,SG,6-7,210,23.0,NaN,NaN
409,Greg Smith,Minnesota Timberwolves,4,PF,6-1,250,25.0,NaN,Fresno State

In [ ]:
#Find salary of player with lowest salary
df.sort_values(by = 'Salary', ascending = True)

,Name,Team,Chest_Number,Position,Height,Weight(lbs),Age,Salary,College
32,Thanasis Antetokounmpo,New York Knicks,43,SF,7-4,205,23.0,30888.0,NaN
130,Phil Pressey,Phoenix Suns,25,PG,5-11,175,25.0,55722.0,Missouri
291,Orlando Johnson,New Orleans Pelicans,0,SG,6-5,220,27.0,55722.0,UC Santa Barbara
135,Alan Williams,Phoenix Suns,15,C,6-8,260,23.0,83397.0,UC Santa Barbara
175,Jordan McRae,Cleveland Cavaliers,12,SG,6-5,179,25.0,111196.0,Tennessee
...,...,...,...,...,...,...,...,...,...
273,Alex Stepheson,Memphis Grizzlies,35,PF,6-1,270,28.0,NaN,USC
350,Briante Weber,Miami Heat,12,PG,6-2,165,23.0,NaN,Virginia Commonwealth
353,Dorell Wright,Miami Heat,11,SF,6-9,205,30.0,NaN,NaN
397,Axel Toupane,Denver Nuggets,6,SG,6-7,210,23.0,NaN,NaN
409,Greg Smith,Minnesota Timberwolves,4,PF,6-1,250,25.0,NaN,Fresno State

In [ ]:
#Find the number of players weighing above 180 pounds

In [ ]:
df[df['Weight(lbs)'] > 180]['Weight(lbs)'].count()

431

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          454 non-null    object
 1   Team          451 non-null    object
 2   Chest_Number  457 non-null    int64
 3   Position      457 non-null    object
 4   Height        457 non-null    object
 5   Weight(lbs)   457 non-null    int64
 6   Age           454 non-null    float64
 7   Salary        443 non-null    float64
 8   College       375 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 32.3+ KB

In [ ]:
#Filter out all the players with height less than 6-2 and count the number of players
df[df['Height'] > "6-2"]['Height'].count()

330

In [ ]:
#Filter the data with more than 35 years of age
#Find the number of records for the "PF " position
df[(df['Age'] > 35) & (df['Position'] == "PF")].count()

Name            6
Team            6
Chest_Number    6
Position        6
Height          6
Weight(lbs)     6
Age             6
Salary          5
College         3
dtype: int64

In [ ]:
#Which team has highest occurence
df['Team'].value_counts()

New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Portland Trail Blazers    15
Oklahoma City Thunder     15
Denver Nuggets            15
Washington Wizards        15
Miami Heat                15
Charlotte Hornets         15
Atlanta Hawks             15
San Antonio Spurs         15
Houston Rockets           15
Dallas Mavericks          15
Indiana Pacers            15
Chicago Bulls             15
Sacramento Kings          15
Phoenix Suns              15
Los Angeles Lakers        15
Los Angeles Clippers      15
Golden State Warriors     15
Philadelphia 76ers        15
Cleveland Cavaliers       14
Orlando Magic             14
Minnesota Timberwolves    14
Utah Jazz                 14
Detroit Pistons           13
Toronto Raptors           13
Name: Team, dtype: int64

In [ ]:
#Which team has the highest number of youngest players (Age less than or equal to 25) playing in the position of "PF" and "SF"
df[(df['Age'] <= 25) & (df['Position'].isin(["PF","SF"]))]["Team"].value_counts()

Chicago Bulls             6
Milwaukee Bucks           5
Philadelphia 76ers        5
Portland Trail Blazers    5
Houston Rockets           5
Memphis Grizzlies         4
New York Knicks           4
Detroit Pistons           4
Indiana Pacers            4
Golden State Warriors     3
Minnesota Timberwolves    3
Sacramento Kings          3
Orlando Magic             2
Boston Celtics            2
San Antonio Spurs         2
Oklahoma City Thunder     2
Washington Wizards        2
Utah Jazz                 2
New Orleans Pelicans      2
Brooklyn Nets             2
Los Angeles Lakers        2
Toronto Raptors           2
Atlanta Hawks             1
Charlotte Hornets         1
Miami Heat                1
Phoenix Suns              1
Denver Nuggets            1
Los Angeles Clippers      1
Dallas Mavericks          1
Name: Team, dtype: int64

In [ ]:
#what is the sum of the salaries of all the players with chest number 41?
df[df['Chest_Number'] == 41]['Salary'].sum()

22264701.0

In [ ]:
#what is the average salary received by players who are 23 or younger in the team "Chicago Bulls"?
df[(df['Age'] <= 23) & (df['Team'] == 'Chicago Bulls')]['Salary'].mean()

958126.5

In [ ]:
#what is the average age of players from rows 201 to 250?
cond = df.iloc[201:251]
cond['Age'].mean()

26.62

In [ ]:
#What is the average weight of players from rows form 201 to 250?
cond = df.iloc[201:251]
cond["Weight(lbs)"].mean()

223.54

In [ ]:
#what is the average age of players in the team Boston Celtics?
df[(df['Team'] == 'Boston Celtics')]['Age'].mean()

24.733333333333334

In [ ]:
#Calculate BMI of players
#Convert height(inches) to Height(metres)
df["BMI"] = df["Weight(lbs)"] / 2.303

In [ ]:
#Count of players who are from college Texas and average of salaries of players from Texas
df[df['College'] == 'Texas']['Salary'].mean()

8968001.111111112

In [ ]:
#Calculate BMI of players
import pandas as pd
df_sample = pd.read_csv("nba_sample.csv")
df_sample["player_height_m"] = df_sample["player_height"] / 100
df_sample['BMI'] = df_sample['player_weight'] / (df_sample['player_height_m'] ** 2)
df_sample

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season,player_height_m,BMI
0,0,Randy Livingston,HOU,22.0,193.04,94.800728,Louisiana State,USA,1996,2,...,2.4,0.3,0.042,0.071,0.169,0.487,0.248,1996-97,1.9304,25.439997
1,1,Gaylon Nickerson,WAS,28.0,190.50,86.182480,Northwestern Oklahoma,USA,1994,2,...,0.3,8.9,0.030,0.111,0.174,0.497,0.043,1996-97,1.9050,23.748109
2,2,George Lynch,VAN,26.0,203.20,103.418976,North Carolina,USA,1993,1,...,1.9,-8.2,0.106,0.185,0.175,0.512,0.125,1996-97,2.0320,25.046833
3,3,George McCloud,LAL,30.0,203.20,102.058200,Florida State,USA,1989,1,...,1.7,-2.7,0.027,0.111,0.206,0.527,0.125,1996-97,2.0320,24.717270
4,4,George Zidek,DEN,23.0,213.36,119.748288,UCLA,USA,1995,1,...,0.3,-14.1,0.102,0.169,0.195,0.500,0.064,1996-97,2.1336,26.305303
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12839,12839,Joel Embiid,PHI,29.0,213.36,127.005760,Kansas,Cameroon,2014,1,...,4.2,8.8,0.057,0.243,0.370,0.655,0.233,2022-23,2.1336,27.899564
12840,12840,John Butler Jr.,POR,20.0,213.36,86.182480,Florida State,USA,Undrafted,Undrafted,...,0.6,-16.1,0.012,0.065,0.102,0.411,0.066,2022-23,2.1336,18.931847
12841,12841,John Collins,ATL,25.0,205.74,102.511792,Wake Forest,USA,2017,1,...,1.2,-0.2,0.035,0.180,0.168,0.593,0.052,2022-23,2.0574,24.217893
12842,12842,Jericho Sims,NYK,24.0,208.28,113.398000,Texas,USA,2021,2,...,0.5,-6.7,0.117,0.175,0.074,0.780,0.044,2022-23,2.0828,26.140281
12843,12843,JaMychal Green,GSW,33.0,205.74,102.965384,Alabama,USA,Undrafted,Undrafted,...,0.9,-8.2,0.087,0.164,0.169,0.650,0.094,2022-23,2.0574,24.325052

In [ ]:

print(len(df_sample['BMI']))
print(df_sample['BMI'])

for i in range(len(df_sample)) :
  if (df_sample['BMI'][i] <= 18.4):
    df_sample['BMI Evaluation'][i] = 'Underweight'
  else :
    df_sample['BMI Evaluation'][i] = 'Normal'